version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://username:password@db:5432/test
    depends_on:
      - db
    command: >
      sh -c "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app

  db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
